package:
  name: bokeh
  version: 'authenticated_redis'

build:
  number: 201502201504

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    # bokeh
    - python
    - numpy
    - pandas
    - six
    - requests
    - dateutil
    - pyyaml
    - pyzmq
    - tornado >=4.0

    # server
    - flask
    - werkzeug
    - greenlet
    # - redis                [linux or osx]
    # - redis-py             [linux or osx]
    - gevent               [py2k]
    - gevent-websocket     [py2k]
    # - abstract-rendering   [py2k]

    # CLI
    # - click

about:
  home: https://github.com/birdsarah/bokeh
  license: New BSD
